import type { ProfileBuilderOutput } from '../agents/profile-builder';
import type { ApplicabilityMatch } from './applicability-matcher';

// Pure renderers — take the structured agent output, emit the
// human-facing markdown the CLI writes to ./output/. Kept here so they
// can be unit-tested without touching the file system.

export function renderCompanyProfile(
  profile: ProfileBuilderOutput,
  docCount: number,
  totalBytes: number
): string {
  const fmtUnknown = (v: string | number) =>
    v === 'unknown' ? '_unknown_' : String(v);

  const lines: string[] = [
    `# Company profile — ${profile.company_name}`,
    '',
    '_Generated by the Compliance Grid `cg` CLI from documents you provided._',
    `_Source: ${docCount} files (${(totalBytes / 1024).toFixed(1)} KB)._`,
    '',
    '> Review this file before running discovery. Edit anything the model misread; the applicability matcher reads from this file directly, so corrections here flow downstream.',
    '',
    '## Structured profile',
    '',
    `- **Entity type**: ${fmtUnknown(profile.entity_type)}`,
    `- **Primary jurisdiction**: ${fmtUnknown(profile.primary_jurisdiction)}`,
    `- **Other jurisdictions**: ${profile.other_jurisdictions.length > 0 ? profile.other_jurisdictions.join(', ') : '_(none derived)_'}`,
    `- **Sector**: ${profile.sector || '_unknown_'}`,
    `- **Headcount (estimate)**: ${fmtUnknown(profile.headcount_estimate)}`,
    `- **Annual turnover INR (estimate)**: ${fmtUnknown(profile.annual_turnover_inr_estimate)}`,
    `- **Incorporation date**: ${fmtUnknown(profile.incorporation_date)}`,
    '',
    '## What the company does',
    '',
    profile.what_they_do,
    '',
    '## Customers and markets',
    '',
    profile.customers_and_markets,
    '',
    '## Operations and locations',
    '',
    profile.operations_and_locations,
    '',
    '## Workforce notes',
    '',
    profile.workforce_notes,
    '',
    '## Regulatory signals',
    '',
    profile.regulatory_signals,
    '',
    '## Citations',
    '',
  ];
  if (profile.citations.length === 0) {
    lines.push('_No specific citations recorded._');
  } else {
    for (const c of profile.citations) {
      lines.push(`- **${c.claim}** — ${c.source_files.join(', ')}`);
    }
  }
  lines.push('');
  return lines.join('\n');
}

export function renderApplicableSources(
  matches: ApplicabilityMatch[],
  topN = 50
): string {
  const top = matches.slice(0, topN);
  const lines: string[] = [
    '# Applicable regulators',
    '',
    `_Ranked by deterministic score against your profile. Top ${top.length} of ${matches.length} shown._`,
    '',
    '| Score | Regulator (id) | Jurisdiction | Domain | URL |',
    '|---|---|---|---|---|',
  ];
  for (const m of top) {
    lines.push(
      `| ${m.score} | \`${m.entry.id}\` | ${m.entry.jurisdiction} | ${m.entry.domain} | ${m.entry.url} |`
    );
  }
  lines.push('');
  lines.push('## How scoring works');
  lines.push('');
  lines.push('- **+3** for a jurisdiction match (entry jurisdiction in your jurisdictions, or central `IN`).');
  lines.push('- **+2** if your sector typically engages this domain (per the matcher\'s sector→domain hints).');
  lines.push('- **+1** if the domain is universal (tax, legal, corporate, foreign-trade).');
  lines.push('- **+2** if your `regulatory_signals` text in the profile mentions this domain/regulator by name.');
  lines.push('');
  lines.push('Want a different shape? Edit the profile and re-run `npm run cg`.');
  lines.push('');
  return lines.join('\n');
}
